# Author the .blend test fixtures, and export each one with Blender's own glTF exporter.
#
#   npm run blend:fixtures
#
# Each scene below is saved as scripts/fixtures/blend/<name>.blend and exported beside it as
# <name>.glb with the settings export_gltf.py gives the baker. The tests read both: the direct
# reader on the .blend, and the glTF reader on Blender's export, and the two must agree.
#
# **That pairing is the point of committing a binary fixture.** The expectation is produced by a
# separate implementation — Blender evaluating its own file — so the test is not a transcription
# of the reader checked against itself. Every scene is built from numbers written here, so a
# fixture can be regenerated by anyone with Blender and compared byte for byte in what it means.
#
# Licence: Apache-2.0, as the rest of this repository. The files it writes are data authored here.

import math
import os
import sys

import bmesh
import bpy

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from export_gltf import export  # noqa: E402


def fresh():
    bpy.ops.wm.read_factory_settings(use_empty=True)


def link(obj, collection=None):
    (collection or bpy.context.scene.collection).objects.link(obj)
    return obj


def mesh_object(name, verts, faces, smooth=False, collection=None):
    mesh = bpy.data.meshes.new(name)
    mesh.from_pydata(verts, [], faces)
    mesh.update()
    for poly in mesh.polygons:
        poly.use_smooth = smooth
    return link(bpy.data.objects.new(name, mesh), collection)


def material(name, color=(0.8, 0.8, 0.8, 1.0), metallic=0.0, roughness=0.5):
    mat = bpy.data.materials.new(name)
    if mat.node_tree is None:
        mat.use_nodes = True
    bsdf = principled(mat)
    bsdf.inputs['Base Color'].default_value = color
    bsdf.inputs['Metallic'].default_value = metallic
    bsdf.inputs['Roughness'].default_value = roughness
    return mat


def principled(mat):
    for node in mat.node_tree.nodes:
        if node.type == 'BSDF_PRINCIPLED':
            return node
    raise RuntimeError('no Principled BSDF in ' + mat.name)


def cube_data(size=1.0):
    s = size
    verts = [(-s, -s, -s), (s, -s, -s), (s, s, -s), (-s, s, -s),
             (-s, -s, s), (s, -s, s), (s, s, s), (-s, s, s)]
    faces = [(0, 3, 2, 1), (4, 5, 6, 7), (0, 1, 5, 4), (1, 2, 6, 5), (2, 3, 7, 6), (3, 0, 4, 7)]
    return verts, faces


def uv_sphere(name, segments=16, rings=8, radius=1.0):
    mesh = bpy.data.meshes.new(name)
    bm = bmesh.new()
    bmesh.ops.create_uvsphere(bm, u_segments=segments, v_segments=rings, radius=radius,
                              calc_uvs=True)
    bm.to_mesh(mesh)
    bm.free()
    return link(bpy.data.objects.new(name, mesh))


def image(name, size, pixel, non_color=False):
    img = bpy.data.images.new(name, size, size, alpha=True)
    data = []
    for y in range(size):
        for x in range(size):
            data.extend(pixel(x, y))
    img.pixels = data
    img.file_format = 'PNG'
    img.pack()
    if non_color:
        img.colorspace_settings.name = 'Non-Color'
    return img


def save_blend(blend):
    # No `.blend1` beside it: a fixture is regenerated over itself, and Blender keeps the last copy.
    bpy.context.preferences.filepaths.save_version = 0
    bpy.ops.wm.save_as_mainfile(filepath=blend, compress=True)


def save(directory, name):
    blend = os.path.join(directory, name + '.blend')
    save_blend(blend)
    export(os.path.join(directory, name + '.glb'))
    print('fixture: ' + name)


# ---------------------------------------------------------------------------------------------

def scene_mesh(directory):
    """Faces of three, four and many sides, flat and smooth, two UV maps, two materials."""
    fresh()
    red = material('Red', (0.8, 0.1, 0.1, 1.0), 0.0, 0.3)
    steel = material('Steel', (0.6, 0.6, 0.65, 1.0), 1.0, 0.2)

    verts, faces = cube_data()
    box = mesh_object('Box', verts, faces)
    box.data.materials.append(red)
    box.data.materials.append(steel)
    for i, poly in enumerate(box.data.polygons):
        poly.material_index = 1 if i >= 4 else 0
    box.location = (1.0, 2.0, 3.0)
    box.rotation_euler = (0.1, 0.2, 0.3)
    box.scale = (1.0, 2.0, 0.5)

    star = []
    for i in range(10):
        r = 1.0 if i % 2 == 0 else 0.4
        a = i * math.pi / 5
        star.append((r * math.cos(a), r * math.sin(a), 0.0))
    ngon = mesh_object('Star', star, [tuple(range(10))])
    ngon.location = (-3.0, 0.0, 0.0)
    ngon.data.materials.append(red)

    sphere = uv_sphere('Sphere')
    sphere.location = (0.0, -3.0, 0.0)
    for poly in sphere.data.polygons:
        poly.use_smooth = True
    sharp = sphere.data.attributes.new('sharp_edge', 'BOOLEAN', 'EDGE')
    for edge in sphere.data.edges:
        a, b = (sphere.data.vertices[i].co for i in edge.vertices)
        sharp.data[edge.index].value = abs(a.z) < 1e-4 and abs(b.z) < 1e-4
    second = sphere.data.uv_layers.new(name='Lightmap')
    first = sphere.data.uv_layers[0]
    for i, loop in enumerate(first.data):
        second.data[i].uv = (loop.uv.x * 0.5, loop.uv.y * 0.5 + 0.25)
    sphere.data.materials.append(steel)

    pyramid = mesh_object('Pyramid',
                          [(-1, -1, 0), (1, -1, 0), (1, 1, 0), (-1, 1, 0), (0, 0, 1.5)],
                          [(0, 3, 2, 1), (0, 1, 4), (1, 2, 4), (2, 3, 4), (3, 0, 4)],
                          smooth=True)
    pyramid.location = (3.0, 3.0, 0.0)

    # A smooth strip whose middle quad has its corners coincide in pairs, so it has no area and its
    # diagonals cancel: Blender gives it the normal (0, 0, 1) and averages that into its neighbours.
    pinched = mesh_object('Pinched',
                          [(0, 0, 0), (1, 0, 0), (1, 1, 0.3), (0, 1, 0.3), (0, 1, 0.3), (1, 1, 0.3),
                           (1, 2, 0.0), (0, 2, 0.0)],
                          [(0, 1, 2, 3), (3, 2, 5, 4), (4, 5, 6, 7)], smooth=True)
    pinched.location = (-3.0, 3.0, 0.0)
    save(directory, 'mesh')


def scene_hierarchy(directory):
    """Parents, every rotation mode, delta transforms, a mirror, instancing, and what is hidden."""
    fresh()
    verts, faces = cube_data(0.25)
    root = link(bpy.data.objects.new('Root', None))
    root.location = (0.0, 0.0, 1.0)
    root.rotation_mode = 'QUATERNION'
    root.rotation_quaternion = (0.9238795, 0.3826834, 0.0, 0.0)
    root.scale = (2.0, 2.0, 2.0)

    child = mesh_object('Child', verts, faces)
    child.location = (1.0, 0.5, 0.0)
    child.rotation_mode = 'ZXY'
    child.rotation_euler = (0.3, 0.5, 0.7)
    child.delta_location = (0.5, 0.0, 0.0)
    child.delta_rotation_euler = (0.0, 0.0, 0.4)
    child.delta_scale = (1.0, 1.0, 1.5)
    bpy.context.view_layer.update()
    child.parent = root
    child.matrix_parent_inverse = root.matrix_world.inverted()

    grand = mesh_object('Grandchild', verts, faces)
    grand.parent = child
    grand.rotation_mode = 'AXIS_ANGLE'
    grand.rotation_axis_angle = (0.6, 1.0, 1.0, 0.0)
    grand.location = (0.0, 1.0, 0.0)

    mirrored = mesh_object('Mirrored', verts, faces)
    mirrored.location = (-2.0, 0.0, 0.0)
    mirrored.scale = (-1.0, 1.0, 1.0)

    hidden = mesh_object('Hidden', verts, faces)
    hidden.hide_render = True
    seen = mesh_object('SeenChild', verts, faces)
    seen.parent = hidden
    seen.location = (0.0, 0.0, -3.0)

    excluded = bpy.data.collections.new('Excluded')
    bpy.context.scene.collection.children.link(excluded)
    mesh_object('ExcludedCube', verts, faces, collection=excluded)
    bpy.context.view_layer.layer_collection.children['Excluded'].exclude = True

    off = bpy.data.collections.new('Off')
    bpy.context.scene.collection.children.link(off)
    off.hide_render = True
    mesh_object('OffCube', verts, faces, collection=off)

    nested = bpy.data.collections.new('Nested')
    bpy.context.scene.collection.children.link(nested)
    inner = bpy.data.collections.new('Inner')
    nested.children.link(inner)
    kept = mesh_object('InnerCube', verts, faces, collection=inner)
    kept.location = (0.0, -2.0, 0.0)

    props = bpy.data.collections.new('Props')
    props.instance_offset = (1.0, 0.0, 0.0)
    a = mesh_object('PropA', verts, faces, collection=props)
    a.location = (1.0, 0.0, 0.0)
    b = mesh_object('PropB', verts, faces, collection=props)
    b.location = (1.0, 1.0, 0.0)
    instance = link(bpy.data.objects.new('Instance', None))
    instance.instance_type = 'COLLECTION'
    instance.instance_collection = props
    instance.location = (5.0, 0.0, 0.0)
    instance.rotation_euler = (0.0, 0.0, math.pi / 2)
    save(directory, 'hierarchy')


def scene_normals(directory):
    """Custom normals in both encodings, sharp edges by angle, and mixed flat and smooth faces."""
    fresh()
    verts, faces = cube_data()
    custom = mesh_object('Custom', verts, faces, smooth=True)
    normals = []
    for loop in custom.data.loops:
        p = custom.data.vertices[loop.vertex_index].co
        n = (p.x * 0.2, p.y * 0.2, 1.0 if p.z > 0 else -1.0)
        length = math.sqrt(n[0] ** 2 + n[1] ** 2 + n[2] ** 2)
        normals.append((n[0] / length, n[1] / length, n[2] / length))
    custom.data.normals_split_custom_set(normals)

    free = mesh_object('Free', verts, faces, smooth=True)
    free.location = (3.0, 0.0, 0.0)
    attribute = free.data.attributes.new('custom_normal', 'FLOAT_VECTOR', 'POINT')
    for i, v in enumerate(free.data.vertices):
        n = v.co.normalized()
        attribute.data[i].vector = (n.x, n.y * 0.5, n.z)

    cylinder = bpy.data.meshes.new('Cylinder')
    bm = bmesh.new()
    bmesh.ops.create_cone(bm, cap_ends=True, segments=12, radius1=1.0, radius2=1.0, depth=2.0)
    bm.to_mesh(cylinder)
    bm.free()
    cyl = link(bpy.data.objects.new('Cylinder', cylinder))
    cyl.location = (-3.0, 0.0, 0.0)
    for poly in cylinder.polygons:
        poly.use_smooth = True
    cylinder.set_sharp_from_angle(angle=math.radians(30))

    mixed = mesh_object('Mixed', [(0, 0, 0), (1, 0, 0), (2, 0, 0.5), (0, 1, 0), (1, 1, 0.2),
                                  (2, 1, 0.7)],
                        [(0, 1, 4, 3), (1, 2, 5, 4)])
    mixed.data.polygons[1].use_smooth = True
    mixed.location = (0.0, 3.0, 0.0)
    save(directory, 'normals')


def scene_materials(directory):
    """Images packed into the file, the usual Principled wiring, alpha, glass and a label."""
    fresh()
    albedo = image('albedo', 4, lambda x, y: (x / 3, y / 3, 0.5, 1.0 if x < 3 else 0.25))
    normal = image('normal', 4, lambda x, y: (0.5 + 0.1 * x, 0.5, 1.0, 1.0), non_color=True)
    orm = image('orm', 4, lambda x, y: (1.0, 0.25 * y, 0.25 * x, 1.0), non_color=True)

    def plane(name, mat, x):
        obj = mesh_object(name, [(-1, -1, 0), (1, -1, 0), (1, 1, 0), (-1, 1, 0)],
                          [(0, 1, 2, 3)])
        uv = obj.data.uv_layers.new(name='UVMap')
        for i, (u, v) in enumerate([(0, 0), (1, 0), (1, 1), (0, 1)]):
            uv.data[i].uv = (u, v)
        obj.data.materials.append(mat)
        obj.location = (x, 0.0, 0.0)
        return obj

    painted = material('Painted')
    nodes, links = painted.node_tree.nodes, painted.node_tree.links
    bsdf = principled(painted)
    tex = nodes.new('ShaderNodeTexImage')
    tex.image = albedo
    links.new(tex.outputs['Color'], bsdf.inputs['Base Color'])
    links.new(tex.outputs['Alpha'], bsdf.inputs['Alpha'])
    painted.surface_render_method = 'BLENDED'
    ntex = nodes.new('ShaderNodeTexImage')
    ntex.image = normal
    nmap = nodes.new('ShaderNodeNormalMap')
    nmap.inputs['Strength'].default_value = 0.8
    links.new(ntex.outputs['Color'], nmap.inputs['Color'])
    links.new(nmap.outputs['Normal'], bsdf.inputs['Normal'])
    otex = nodes.new('ShaderNodeTexImage')
    otex.image = orm
    split = nodes.new('ShaderNodeSeparateColor')
    links.new(otex.outputs['Color'], split.inputs['Color'])
    links.new(split.outputs['Green'], bsdf.inputs['Roughness'])
    links.new(split.outputs['Blue'], bsdf.inputs['Metallic'])
    plane('PaintedPlane', painted, 0.0)

    glow = material('Glow', (0.0, 0.0, 0.0, 1.0))
    principled(glow).inputs['Emission Color'].default_value = (1.0, 0.5, 0.0, 1.0)
    principled(glow).inputs['Emission Strength'].default_value = 3.0
    plane('GlowPlane', glow, 3.0)

    glass = material('Glass', (0.9, 0.95, 1.0, 1.0), 0.0, 0.05)
    principled(glass).inputs['Transmission Weight'].default_value = 1.0
    plane('GlassPlane', glass, 6.0)

    culled = material('Culled', (0.2, 0.4, 0.8, 1.0))
    culled.use_backface_culling = True
    culled['substance'] = 'oak'
    plane('CulledPlane', culled, 9.0)

    faded = material('Faded', (0.3, 0.8, 0.3, 1.0))
    principled(faded).inputs['Alpha'].default_value = 0.4
    faded.surface_render_method = 'BLENDED'
    plane('FadedPlane', faded, 12.0)

    clipped = material('Clipped')
    nodes, links = clipped.node_tree.nodes, clipped.node_tree.links
    tex = nodes.new('ShaderNodeTexImage')
    tex.image = albedo
    clip = nodes.new('ShaderNodeMath')
    clip.operation = 'GREATER_THAN'
    clip.inputs[1].default_value = 0.3
    links.new(tex.outputs['Color'], principled(clipped).inputs['Base Color'])
    links.new(tex.outputs['Alpha'], clip.inputs[0])
    links.new(clip.outputs['Value'], principled(clipped).inputs['Alpha'])
    plane('ClippedPlane', clipped, 15.0)

    tinted = material('Tinted')
    nodes, links = tinted.node_tree.nodes, tinted.node_tree.links
    tex = nodes.new('ShaderNodeTexImage')
    tex.image = albedo
    mix = nodes.new('ShaderNodeMix')
    mix.data_type = 'RGBA'
    mix.blend_type = 'MULTIPLY'
    mix.inputs['Factor'].default_value = 1.0
    mix.inputs[7].default_value = (0.5, 1.0, 1.0, 1.0)
    links.new(tex.outputs['Color'], mix.inputs[6])
    links.new(mix.outputs[2], principled(tinted).inputs['Base Color'])
    plane('TintedPlane', tinted, 18.0)

    painted_by = material('ByAttribute')
    nodes, links = painted_by.node_tree.nodes, painted_by.node_tree.links
    attribute = nodes.new('ShaderNodeVertexColor')
    attribute.layer_name = 'Col'
    links.new(attribute.outputs['Color'], principled(painted_by).inputs['Base Color'])
    coloured = plane('AttributePlane', painted_by, 21.0)
    col = coloured.data.color_attributes.new('Col', 'BYTE_COLOR', 'CORNER')
    for i, rgba in enumerate([(1, 0, 0, 1), (0, 1, 0, 1), (0, 0, 1, 1), (1, 1, 0, 1)]):
        col.data[i].color = rgba
    save(directory, 'materials')


def scene_shapes(directory):
    """Shape keys at a weight, which the exporter writes as morph targets."""
    fresh()
    verts = [(x, y, 0.0) for y in range(3) for x in range(3)]
    faces = [(0, 1, 4, 3), (1, 2, 5, 4), (3, 4, 7, 6), (4, 5, 8, 7)]
    grid = mesh_object('Grid', verts, faces)
    grid.shape_key_add(name='Basis')
    up = grid.shape_key_add(name='Up')
    up.data[4].co.z = 1.0
    up.value = 0.25
    side = grid.shape_key_add(name='Side')
    side.data[2].co.x = 3.0
    side.value = 0.0
    save(directory, 'shapes')


def scene_lights(directory):
    """A point, a spot and a sun, each in its own colour."""
    fresh()

    def lamp(name, kind, energy, color, location, rotation=(0.0, 0.0, 0.0)):
        data = bpy.data.lights.new(name, kind)
        data.energy = energy
        data.color = color
        obj = link(bpy.data.objects.new(name, data))
        obj.location = location
        obj.rotation_euler = rotation
        return data

    lamp('Bulb', 'POINT', 100.0, (1.0, 0.9, 0.8), (0.0, 0.0, 2.0))
    spot = lamp('Spot', 'SPOT', 500.0, (0.6, 0.8, 1.0), (2.0, 0.0, 3.0), (0.4, 0.0, 0.0))
    spot.spot_size = math.radians(45)
    spot.spot_blend = 0.2
    lamp('Sun', 'SUN', 3.0, (1.0, 1.0, 0.9), (0.0, 0.0, 10.0), (0.5, 0.2, 0.0))
    warm = lamp('Warm', 'POINT', 60.0, (1.0, 1.0, 1.0), (-4.0, 0.0, 2.0))
    warm.use_temperature = True
    warm.temperature = 3000.0
    area = lamp('Panel', 'AREA', 50.0, (1.0, 1.0, 1.0), (-2.0, 0.0, 3.0))
    area.size = 0.5
    mesh_object('Ground', [(-5, -5, 0), (5, -5, 0), (5, 5, 0), (-5, 5, 0)], [(0, 1, 2, 3)])
    save(directory, 'lights')


def scene_modifiers(directory):
    """A modifier the direct reader cannot evaluate, which is what delegation exists for."""
    fresh()
    verts, faces = cube_data()
    cube = mesh_object('Subdivided', verts, faces, smooth=True)
    sub = cube.modifiers.new('Subdivision', 'SUBSURF')
    sub.levels = 2
    sub.render_levels = 2
    off = mesh_object('ViewportOnly', verts, faces)
    off.location = (3.0, 0.0, 0.0)
    viewport = off.modifiers.new('Preview', 'SUBSURF')
    viewport.show_render = False
    save(directory, 'modifiers')


def scene_rig(directory):
    """Three bones, a skinned column, a pose, and an action that bends it."""
    fresh()
    armature = bpy.data.armatures.new('Rig')
    rig = link(bpy.data.objects.new('Rig', armature))
    bpy.context.view_layer.objects.active = rig
    bpy.ops.object.mode_set(mode='EDIT')
    previous = None
    for i, name in enumerate(['Root', 'Mid', 'Tip']):
        bone = armature.edit_bones.new(name)
        bone.head = (0.0, 0.0, float(i))
        bone.tail = (0.0, 0.0, float(i + 1))
        bone.roll = 0.3 * i
        if previous is not None:
            bone.parent = previous
            bone.use_connect = True
        previous = bone
    bpy.ops.object.mode_set(mode='OBJECT')

    verts = []
    faces = []
    for ring in range(7):
        z = ring * 0.5
        for corner, (x, y) in enumerate([(-0.2, -0.2), (0.2, -0.2), (0.2, 0.2), (-0.2, 0.2)]):
            verts.append((x, y, z))
    for ring in range(6):
        for side in range(4):
            a = ring * 4 + side
            b = ring * 4 + (side + 1) % 4
            faces.append((a, b, b + 4, a + 4))
    column = mesh_object('Column', verts, faces, smooth=True)
    for name in ['Root', 'Mid', 'Tip']:
        column.vertex_groups.new(name=name)
    for i, v in enumerate(column.data.vertices):
        z = v.co.z
        root_w = max(0.0, 1.0 - z)
        tip_w = max(0.0, z - 2.0)
        mid_w = max(0.0, 1.0 - abs(z - 1.5) / 1.5)
        total = root_w + mid_w + tip_w
        for name, w in (('Root', root_w), ('Mid', mid_w), ('Tip', tip_w)):
            if w > 0:
                column.vertex_groups[name].add([i], w / total, 'REPLACE')
    column.parent = rig
    modifier = column.modifiers.new('Armature', 'ARMATURE')
    modifier.object = rig

    rig.pose.bones['Mid'].rotation_quaternion = (0.9659258, 0.2588190, 0.0, 0.0)
    rig.animation_data_create()
    action = bpy.data.actions.new('Bend')
    rig.animation_data.action = action
    for frame, angle in ((1, 0.0), (20, 0.5)):
        pose = rig.pose.bones['Tip']
        pose.rotation_quaternion = (math.cos(angle / 2), 0.0, math.sin(angle / 2), 0.0)
        pose.keyframe_insert('rotation_quaternion', frame=frame)
    bpy.context.scene.frame_set(1)
    save(directory, 'rig')


def scene_motion(directory):
    """Object animation three ways: keyed Bezier, a Cycles loop, and an NLA strip repeated."""
    fresh()
    verts, faces = cube_data(0.3)
    scene = bpy.context.scene
    scene.frame_start = 1
    scene.frame_end = 90

    keyed = mesh_object('Keyed', verts, faces)
    for frame, loc, rot in ((1, (0, 0, 0), (0, 0, 0)), (30, (2, 1, 0.5), (0, 0, 1.2)), (60, (4, -1, 0), (0.5, 0, 2.4))):
        keyed.location = loc
        keyed.rotation_euler = rot
        keyed.keyframe_insert('location', frame=frame)
        keyed.keyframe_insert('rotation_euler', frame=frame)

    looping = mesh_object('Looping', verts, faces)
    looping.location = (0, 3, 0)
    for frame, z in ((1, 0.0), (11, 1.0), (21, 0.0)):
        looping.location.z = z
        looping.keyframe_insert('location', index=2, frame=frame)
    _cycles(looping)

    strip = mesh_object('Strip', verts, faces)
    strip.location = (0, -3, 0)
    for frame, x in ((1, 0.0), (11, 2.0)):
        strip.location.x = x
        strip.keyframe_insert('location', index=0, frame=frame)
    action = strip.animation_data.action
    strip.animation_data.action = None
    track = strip.animation_data.nla_tracks.new()
    nla = track.strips.new('Slide', 10, action)
    nla.repeat = 2.0
    nla.scale = 1.5
    nla.extrapolation = 'HOLD'
    scene.frame_set(1)
    blend = os.path.join(directory, 'motion.blend')
    save_blend(blend)
    export(os.path.join(directory, 'motion.glb'), {'export_animation_mode': 'SCENE', 'export_force_sampling': True, 'export_frame_step': 1})
    print('fixture: motion')


def _cycles(obj):
    """A Cycles modifier on every F-curve of an object's action, layered or not."""
    action = obj.animation_data.action
    curves = []
    if hasattr(action, 'layers') and len(action.layers) > 0:
        for layer in action.layers:
            for strip in layer.strips:
                for bag in strip.channelbags:
                    curves.extend(bag.fcurves)
    elif hasattr(action, 'fcurves'):
        curves = list(action.fcurves)
    for curve in curves:
        if not any(m.type == 'CYCLES' for m in curve.modifiers):
            curve.modifiers.new('CYCLES')


SCENES = {
    'mesh': scene_mesh,
    'hierarchy': scene_hierarchy,
    'normals': scene_normals,
    'materials': scene_materials,
    'shapes': scene_shapes,
    'lights': scene_lights,
    'modifiers': scene_modifiers,
    'rig': scene_rig,
    'motion': scene_motion,
}


if __name__ == '__main__':
    argv = sys.argv[sys.argv.index('--') + 1:] if '--' in sys.argv else []
    directory = argv[0]
    wanted = argv[1:] or list(SCENES)
    for name in wanted:
        SCENES[name](directory)
