import { expect, test } from 'vitest';
import { fetchAudioManifest, parseAudioManifest } from './manifest.ts';

test('the order is the manifest sorted, not the order it arrived in', () => {
  /*
   * The caller picks one entry by seed, and that pick has to land on the same
   * asset for every player. A manifest is generated by walking a directory, and
   * directory order is filesystem order — it differs between machines and even
   * between builds. Two players on the same day would get different music, and
   * "everyone shares today" would quietly stop being true for the one thing
   * nobody would think to check.
   */
  expect(parseAudioManifest(['zulu', 'alpha', 'mike'])).toEqual(['alpha', 'mike', 'zulu']);
});

test('one bad entry costs that entry and nothing else', () => {
  // The manifest is machine-written, and a generator bug must not take down a
  // library that is otherwise fine.
  expect(parseAudioManifest(['good', 42, null, '', '  ', 'also-good'])).toEqual([
    'also-good',
    'good',
  ]);
});

test('an entry is a slot name, never a path', () => {
  /*
   * Names go straight into a URL. A manifest that can say `../../secrets` or
   * `evil.mp3` is a manifest that decides what gets fetched — and the file is
   * generated, so the day it is generated from something less trusted than a
   * local folder, this is the check that was already there.
   */
  expect(parseAudioManifest(['../escape', 'a/b', 'c\\d', 'track.mp3', 'fine'])).toEqual(['fine']);
});

test('duplicates collapse', () => {
  // Two formats of the same track produce the same base name twice.
  expect(parseAudioManifest(['track', 'track'])).toEqual(['track']);
});

test('anything that is not a list is an empty library', () => {
  for (const junk of [null, undefined, 42, 'nope', {}]) {
    expect(parseAudioManifest(junk)).toEqual([]);
  }
});

test('a missing manifest is silence, not a failure', async () => {
  /*
   * The whole asset system is built so the game runs with no files at all. A
   * folder nobody has scanned yet must behave exactly like an empty one —
   * throwing here would take down audio on a fresh checkout.
   */
  const missing = await fetchAudioManifest(
    '/audio/tracks.json',
    async () => new Response('', { status: 404 }),
  );
  expect(missing).toEqual([]);

  const broken = await fetchAudioManifest(
    '/audio/tracks.json',
    async () => new Response('{not json', { status: 200 }),
  );
  expect(broken).toEqual([]);

  const offline = await fetchAudioManifest('/audio/tracks.json', () => {
    throw new Error('offline');
  });
  expect(offline).toEqual([]);
});

test('a real manifest comes back parsed and sorted', async () => {
  const names = await fetchAudioManifest(
    '/audio/tracks.json',
    async () => new Response(JSON.stringify(['dusk-run', 'atlas', 'atlas']), { status: 200 }),
  );
  expect(names).toEqual(['atlas', 'dusk-run']);
});
