import type { FetchLike } from './registry.ts';

/**
 * Discovering how many sound assets exist, without a hard limit.
 *
 * A browser cannot list a directory, so an asset folder has to announce itself
 * somehow. The three options are a fixed list in code (which caps the library
 * at whatever number somebody typed), probing upward until requests start
 * failing (a burst of 404s on every load, and one gap in the numbering silently
 * truncates the set), or a manifest.
 *
 * A manifest, generated from the folder at build time, is the only one of the
 * three with no ceiling and no wasted requests. Adding an asset stays a matter
 * of dropping the file in; the manifest catches up on the next build.
 *
 * Deliberately not a game concept: this returns names, and the caller decides
 * that some of them are music.
 */

/** Every name in a manifest, or an empty list if there is not one. */
export async function fetchAudioManifest(
  url: string,
  // platform: browser default — `FetchLike` is the seam and this is its default
  fetchImpl: FetchLike = (target) => fetch(target),
): Promise<string[]> {
  let parsed: unknown;
  try {
    const response = await fetchImpl(url);
    if (!response.ok) return [];
    parsed = await response.json();
  } catch {
    /*
     * A missing or unreadable manifest is silence, never a failure. The whole
     * asset system is built so a game runs with no files at all — a folder that
     * has not been scanned yet must behave exactly like an empty one.
     */
    return [];
  }
  return parseAudioManifest(parsed);
}

/**
 * Validate a manifest's contents.
 *
 * Separated from fetching so the rules can be tested without a network, and
 * because the rules are the part that matters: a manifest is generated by a
 * script, and a script that emits one bad entry must not take the rest of the
 * library down with it.
 */
export function parseAudioManifest(value: unknown): string[] {
  if (!Array.isArray(value)) return [];

  const names: string[] = [];
  const seen = new Set<string>();
  for (const entry of value) {
    if (typeof entry !== 'string') continue;
    const name = entry.trim();
    if (name.length === 0 || seen.has(name)) continue;
    // A name is a slot, not a path. Anything with a separator or an extension
    // in it is a generator bug, and following it would mean fetching whatever
    // the manifest asked for from wherever it asked.
    if (name.includes('/') || name.includes('\\') || name.includes('.')) continue;
    seen.add(name);
    names.push(name);
  }
  /*
   * Sorted, because the caller picks one by seed and that pick has to be the
   * same everywhere. Directory order is filesystem order, which differs between
   * machines — two players on the same day would get different music, and the
   * daily would quietly stop being shared.
   */
  names.sort();
  return names;
}
