/**
 * Write the checked-in `.drft` fixture for the current version.
 *
 * Run **once per released minor version** and never again for a version already written:
 *
 *   node scripts/drft-fixture.mjs 1.0
 *
 * The fixtures are the compatibility promise made testable. `drftCompat.test.ts` opens
 * every one of them with today's reader, so what is under test is whether *old bytes*
 * still load — which is the actual claim. A fixture regenerated by a newer writer tests
 * that the writer agrees with the reader, which they always will, and proves nothing.
 *
 * A base64 module rather than a binary file on purpose: it survives a repository that
 * normalises line endings, it diffs as text so an accidental regeneration is obvious in
 * review, and it needs no loader in the test.
 */

import { writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const version = process.argv[2];
if (version === undefined || !/^\d+\.\d+$/.test(version)) {
  console.error('usage: node scripts/drft-fixture.mjs <major>.<minor>   e.g. 1.0');
  process.exit(1);
}

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, '..');
const out = path.join(root, 'packages/drft/src/fixtures', `v${version.replace('.', '-')}.ts`);

/*
 * Built through vitest rather than by importing the TypeScript directly, because the
 * engine ships as source and has no build step — this is the one place that needs the
 * sources executed outside a test run.
 */
const script = `
import { writeFileSync } from 'node:fs';
import { MeshBuilder } from './packages/core/src/geometry/meshBuilder';
import { writeDrft } from './packages/drft/src/drftWrite';

const builder = new MeshBuilder().setRoughness(0.3).setGrain(0.7).setEmissiveColor([0.2, 0.4, 0.9]);
builder.addBox([0, 0, 0], [1, 2, 3], [0.5, 0.6, 0.7], 0.25, 0.4);
builder.addSphere([4, 0, 0], 1, [0.9, 0.1, 0.2], 0.1, 10, 5);
const plain = new MeshBuilder();
plain.addBox([9, 0, 0], [0.5, 0.5, 0.5], [0.1, 0.2, 0.3], 0, 0);

/*
 * A coarse level, which is what 1.2 added. Written by hand rather than decimated, because a
 * fixture is about the *bytes of the chunk* and not about the quality of a decimation: one box
 * standing in for the asset is a complete LODM payload and stays readable for ever.
 */
const coarse = new MeshBuilder();
coarse.addBox([4, 0, 0], [5, 2, 3], [0.4, 0.4, 0.45], 0, 0);

/*
 * A rig, which is what 1.6 added: a hierarchy, a two-joint skin and one clip. Small on purpose —
 * a fixture is about the bytes of the chunks and not about the quality of the animation, and two
 * joints exercise every field a hundred would.
 */
const identity = (n) => {
  const out = new Float32Array(n * 16);
  for (let i = 0; i < n; i++) { out[i * 16] = 1; out[i * 16 + 5] = 1; out[i * 16 + 10] = 1; out[i * 16 + 15] = 1; }
  return out;
};
const rig = ${
  version >= '1.6'
    ? `{
  nodes: [
    { parent: -1, translation: [0, 0, 0], rotation: [0, 0, 0, 1], scale: [1, 1, 1], mesh: 0, name: 'root' },
    { parent: 0, translation: [0, 2, 0], rotation: [0, 0, 0, 1], scale: [1, 1, 1], mesh: -1, name: 'hanger' },
  ],
  skins: [{
    joints: [{ parent: -1, name: 'root' }, { parent: 0, name: 'elbow' }],
    inverseBind: identity(2),
  }],
  clips: [{
    name: 'walk',
    durationSec: 1.5,
    tracks: [
      { joint: 1, path: 'rotation', times: new Float32Array([0, 1.5]), values: new Float32Array([0, 0, 0, 1, 0, 1, 0, 0]) },
      { joint: 0, path: 'translation', times: new Float32Array([0]), values: new Float32Array([2, 0, 0]) },
    ],
  }],
}`
    : '{}'
};

/*
 * Morph deltas on the second mesh, which is what 1.7 added. Two targets over a small box, so the
 * chunk exercises the mesh-ordinal pairing — the first mesh has none, so a reader pairing by the
 * chunk's own ordinal would deform the wrong one.
 */
const plainMesh = plain.build();
const morphed = ${
  version >= '1.7'
    ? `(() => {
  const vertices = plainMesh.positions.length / 3;
  const deltas = new Float32Array(vertices * 2 * 3);
  for (let v = 0; v < vertices; v++) {
    deltas[(v * 2 + 0) * 3 + 0] = 0.25;
    deltas[(v * 2 + 1) * 3 + 1] = 0.5;
  }
  return { ...plainMesh, morphTargets: deltas, morphTargetCount: 2 };
})()`
    : 'plainMesh'
};

const buffer = writeDrft({
  meshes: [builder.build(), morphed],
  lods: [coarse.build()],
  ...rig,
  head: { name: 'fixture', generator: 'drft-fixture ${version}' },
});
writeFileSync(process.env.DRFT_OUT, Buffer.from(buffer).toString('base64'));
`;

const tmp = path.join(root, '.drft-fixture.tmp.ts');
const raw = path.join(root, '.drft-fixture.b64');
writeFileSync(tmp, script);
try {
  execFileSync('npx', ['tsx', tmp], { cwd: root, env: { ...process.env, DRFT_OUT: raw } });
} finally {
  execFileSync('rm', ['-f', tmp]);
}

const base64 = execFileSync('cat', [raw]).toString();
execFileSync('rm', ['-f', raw]);

writeFileSync(
  out,
  `/**
 * A \`.drft\` written by version ${version}, kept byte for byte.
 *
 * **Never regenerate this file.** It exists so today's reader can be tested against
 * genuinely old bytes; rewriting it with a newer writer would only prove that the writer
 * and the reader agree, which they always do, and would silently retire the guarantee it
 * is here to defend.
 */
export const FIXTURE_V${version.replace('.', '_')} =
  '${base64.trim()}';
`,
);
console.log(`wrote ${path.relative(root, out)} (${base64.length} base64 chars)`);
